FROM pgadmin
LABEL maintainer="gustavoleandrogorges@gmail.com"

# RUN executa comandos em um shell dentro do container para construir a imagem. 
# O resultado da execução do comando é armazenado no sistema de arquivos da 
# imagem como uma nova camada.
# Agrupar os comandos em um único RUN pode reduzir a quantidade de camadas da 
# imagem e torná-la mais eficiente.
RUN chmod a+rwx /var/lib/pgadmin/sessions
