version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - .docker/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: 'root@root.com.br'
      PGADMIN_DEFAULT_PASSWORD: 'root'
    ports:
      - '16543:80'
    volumes:
      - .docker/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
